name: Run building and testing Spark on ARM64

on:
  pull_request:
    branches:
      - master

env:
  ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
  SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
  REGION: "ap-southeast-1"
  PROJECT_ID: "948727b76f77426a8209e7581626cb5a"
  CLUSTER_ID: "3c4b534c-c02d-11eb-9aed-0255ac101fc1"
  ALLUXIO_IMG: "ghcr.io/liusheng/alluxio-aarch64:latest"

jobs:
  build-on-arm64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get kubectl
        run: |
          curl -sL https://dl.k8s.io/v1.19.0/kubernetes-client-linux-amd64.tar.gz | tar zx -C $HOME/
          export PATH=PATH:$HOME/kubernetes/client/bin

      - uses: huaweicloud/cce-cluster-credentials@v1
        with:
          region: "${{ env.REGION }}"
          access-key-id: "${{ env.ACCESS_KEY_ID }}"
          access-key-secret: "${{ env.SECRET_ACCESS_KEY }}"
          project-id: "${{ env.PROJECT_ID }}"
          cluster-id: "${{ env.CLUSTER_ID }}"

      - name: Run with specific image
        run: |-
          kubectl config use-context external
          kubectl run --rm -i --privileged=true --image "${{ env.ALLUXIO_IMG }}" spark-test
